### ISSUE TITLE
Add support for multiple machineDeployments

### ISSUE THREAD

**Issue by eigenpaul** [SovereignCloudStack/capi-jsgen#8]
In the current state only the replicas field gets duplicated when adding a new machineDeployment.
Ideally it should allow multiple deployments:

```
      machineDeployments:
        - class: openstack-scs-1-30-v1
          failureDomain: nova
          name: md0
          replicas: 1
        - class: openstack-scs-1-31-v1
          failureDomain: nova
          name: md0
          replicas: 1
```
